name: movidius-test
version: '0.1'
summary: Test snap for Intel Movidius in Ubuntu Core # 79 char long summary
description: |
  This is an exmaple of how to run Intel OpenVINO libraries for Computer Vision, 
  using the Intel Neural Compute Stick USB accelerator.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  # Main module, contains the python code
  movidius-test:
    # See 'snapcraft plugins'
    plugin: python
    stage-packages:
      # TODO: Cleanup stage-packages, some might not be needed for a minimum install
      - libcairo2-dev
      - libpango1.0-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libswscale-dev
      - libavcodec-dev
      - libavformat-dev
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - build-essential
      - cmake
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libdrm-dev
      - libpng-dev
      - libpython3.5

  # Copy OpenVINO installed libraries into the snap
  openvino:
    plugin: dump
    source: openvino

# Test App to expose
apps:
  movidius-test:
    command: test
    
environment:
  # TODO: Check all of these envs, some might not be needed
  # TODO: Make updateable from external script
  INSTALLDIR: $SNAP/openvino_2019.1.144
  INTEL_OPENVINO_DIR: $SNAP/openvino_2019.1.144
  INTEL_CVSDK_DIR: $SNAP/openvino_2019.1.144
  HDDL_INSTALL_DIR: $SNAP/openvino_2019.1.144/deployment_tools/inference_engine/external/hddl
  IE_PLUGINS_PATH: $SNAP/openvino_2019.1.144/deployment_tools/inference_engine/lib/intel64
  ARCH_ROOT_DIR: $SNAP/openvino_2019.1.144/deployment_tools/inference_engine/lib/intel64/arch_descriptions
  InferenceEngine_DIR: $SNAP/openvino_2019.1.144/deployment_tools/inference_engine/share
  OpenCV_DIR: $SNAP/openvino_2019.1.144/opencv/cmake
  PATH: $SNAP/openvino_2019.1.144/deployment_tools/model_optimizer:$PATH
  PYTHONPATH: $SNAP/lib/python3.5/site-packages:$SNAP/openvino_2019.1.144/deployment_tools/model_optimizer:$SNAP/openvino_2019.1.144/python/python3.5:$PYTHONPATH
  LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/openvino_2019.1.144/openvx/lib:/opt/intel/opencl:$SNAP/openvino_2019.1.144/deployment_tools/inference_engine/external/hddl/lib:$SNAP/openvino_2019.1.144/deployment_tools/inference_engine/external/gna/lib:$SNAP/openvino_2019.1.144/deployment_tools/inference_engine/external/mkltiny_lnx/lib:$SNAP/openvino_2019.1.144/deployment_tools/inference_engine/external/tbb/lib:$SNAP/openvino_2019.1.144/deployment_tools/inference_engine/lib/intel64:$SNAP/openvino_2019.1.144/opencv/lib:$LD_LIBRARY_PATH


